# Generated by Django 4.2.18 on 2026-06-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='ID do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='informe o RG do instrutor', max_length=100)),
                ('nome', models.TimeField(help_text='Informe o nome do instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Informe a data de nascimento', max_length=70, null=True)),
                ('telefone', models.CharField(help_text='Informe o telefone do instrutor', max_length=70, null=True)),
                ('ddd', models.CharField(help_text='Informe o DDD do instrutor', max_length=70, null=True)),
                ('codigoTitulo', models.CharField(help_text='Informe o código do título do instrutor', max_length=70, null=True)),
            ],
        ),
    ]
