# Generated by Django 4.2.18 on 2026-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='rg',
            field=models.CharField(help_text='informe o RG do instrutor', max_length=10),
        ),
    ]
