# Generated by Django 4.2.18 on 2026-06-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_alter_instrutor_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='nome',
            field=models.CharField(help_text='Informe o nome do instrutor', max_length=70),
        ),
    ]
