# Generated by Django 4.2.18 on 2026-06-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0002_alter_titulo_codigo'),
        ('instrutor', '0004_alter_instrutor_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutor',
            name='codigoTitulo',
        ),
        migrations.AddField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='codigo_titulo', help_text='Informe o código do título do instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='dataNascimento',
            field=models.DateField(help_text='Informe a data de nascimento', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='ddd',
            field=models.CharField(help_text='Informe o DDD do instrutor', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='telefone',
            field=models.CharField(help_text='Informe o telefone do instrutor', max_length=9, null=True),
        ),
    ]
