# Generated by Django 4.2.18 on 2026-06-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0002_alter_titulo_codigo'),
        ('instrutor', '0005_remove_instrutor_codigotitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='codigo_titulo', help_text='Informe o código do título do instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrutores', to='titulo.titulo'),
        ),
    ]
