# Generated by Django 4.2.18 on 2026-06-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matrícula do aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do aluno', max_length=100)),
                ('datainicial', models.CharField(help_text='Informe a data inicial do aluno', max_length=70)),
                ('datafinal', models.CharField(help_text='Informe a data final do aluno', max_length=70)),
            ],
        ),
    ]
