# Generated by Django 4.2.18 on 2026-06-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='datafinal',
            field=models.CharField(help_text='Informe a data final do aluno', max_length=70, null=True),
        ),
    ]
