# Generated by Django 4.2.18 on 2026-06-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_datafinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='datafinal',
            field=models.CharField(blank=True, help_text='Informe a data final do aluno', max_length=70, null=True),
        ),
    ]
