# Generated by Django 4.2.18 on 2026-06-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Numero da turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='informe o horario da aula', max_length=100)),
                ('duracaoAula', models.TimeField(help_text='Informe a duração da aula', max_length=70)),
                ('dataInicial', models.DateField(help_text='Informe a data inicial', max_length=70, null=True)),
                ('dataFinal', models.DateField(help_text='Informe a data final', max_length=70, null=True)),
            ],
        ),
    ]
