# Generated by Django 4.2.18 on 2026-06-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigoTipoAtividade',
            field=models.CharField(help_text='Informe o código do tipo de atividade', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='idInstrutor',
            field=models.CharField(help_text='Informe o ID do instrutor', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='matriculaMonitor',
            field=models.CharField(help_text='Informe o registro do monitor', max_length=70, null=True),
        ),
    ]
