# Generated by Django 4.2.18 on 2026-06-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0006_alter_instrutor_codigo_titulo'),
        ('titulo', '0002_alter_titulo_codigo'),
        ('turma', '0002_turma_codigotipoatividade_turma_idinstrutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='codigo_titulo', help_text='Informe o código do título do instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='titulo.titulo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='idInstrutor',
            field=models.ForeignKey(blank=True, db_column='id_instrutor', help_text='Informe o ID do instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='instrutor.instrutor'),
        ),
    ]
